# Generated by Django 6.0 on 2025-12-17 10:25

import cloudinary.models
import datetime
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='src',
        ),
        migrations.RemoveField(
            model_name='video',
            name='src',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='products/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2025, 12, 17, 10, 25, 39, 639086, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='products/videos'),
            preserve_default=False,
        ),
    ]
