# Generated by Django 6.0 on 2025-12-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_user_managers_remove_image_src_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
